spring:
  application:
    name: backend-tutor
  datasource:
    url: jdbc:postgresql://localhost:38121/tutor
    username: lgcms
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 38122
      database: 1
  ai:
    chat:
      memory:
        redis:
          enabled: true
          options:
            capacity: 10
          key-prefix: "lecture_user="
          time-to-live: "2h"
    model:
      embedding: bedrock-titan
      chat: bedrock-converse
    bedrock:
      aws:
        region: ${AWS_REGION}
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      titan:
        embedding:
          model: amazon.titan-embed-text-v2:0
          input-type: text
      converse:
        chat:
          options:
            model: "anthropic.claude-3-haiku-20240307-v1:0"
            max-tokens: 1024
            temperature: 0.3
            search:
              similarity-threshold: 0.5

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        initialize-schema: true
        table-name: tutor_bot_embedded_q
        dimensions: 1024

  kafka:
    bootstrap-servers: http://192.168.0.161:38123
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
      ack-mode: manual

    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 10
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.tutor_bot.common.kafka.dto.KafkaEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 38114  #tutor
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: ${spring.application.name}