spring:
  application:
    name: tutor_bot
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-ada-002
        chat:
          options:
            model: gpt-4o-mini
            temperature: 0.4
            max-tokens: 1500
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        distance-type: COSINE_DISTANCE
#        dimensions: 1536
#        max-document-batch-size: 10000 # ?? ??: ??? ?? ?? ?
#        schema-validation: true
  chat:
    memory:
      repository:
        jdbc:
          initialize-schema: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      open-in-view: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver